// Code generated by payloadgen (export-payload-types); DO NOT EDIT.
// Source of truth: the exported structs of Go package "multi".
// Regenerated by scripts/generate.ts on every install — never committed.

/** Reply references a type from a sibling file. */
export interface Reply {
    ack: Ack
}

/** Ack is declared in the lexically-later file. */
export interface Ack {
    status: string
}
