// Package emoji is the server-side half of the emoji vocabulary.
//
// The reactions column is free text, so the byte string that reaches a unique
// index has to be pinned somewhere. The client normalizes before it writes
// (core/lib/emoji/normalize.ts); this package is what makes that a guarantee
// rather than a hope, because the CLI, the OAuth API and any future writer do
// not go through the picker.
//
// vocabulary.json is GENERATED by core/scripts/build-emoji-data.ts in the same
// pass that writes the TypeScript tables, so the two cannot disagree. Editing
// it by hand would defeat the point.
package emoji

import (
	_ "embed"
	"encoding/json"
	"strings"

	"golang.org/x/text/unicode/norm"
)

//go:embed vocabulary.json
var vocabularyJSON []byte

// maxLength matches the column's max in pb-migrations/1980000013.
const maxLength = 32

var vocabulary struct {
	Canonical []string          `json:"canonical"`
	Tonable   []string          `json:"tonable"`
	ByBare    map[string]string `json:"byBare"`
}

var (
	canonical map[string]struct{}
	tonable   map[string]struct{}
	// byStripped maps a tone-stripped sequence back to its canonical base.
	// Built rather than generated, so it cannot disagree with StripTone.
	byStripped map[string]string
)

// skinTones are the five modifiers, matching core/lib/emoji/tones.ts.
var skinTones = [...]rune{0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}

func init() {
	if err := json.Unmarshal(vocabularyJSON, &vocabulary); err != nil {
		panic("emoji: vocabulary.json is unreadable: " + err.Error())
	}

	canonical = make(map[string]struct{}, len(vocabulary.Canonical))
	for _, glyph := range vocabulary.Canonical {
		canonical[glyph] = struct{}{}
	}

	tonable = make(map[string]struct{}, len(vocabulary.Tonable))
	byStripped = make(map[string]string, len(vocabulary.Tonable))
	for _, glyph := range vocabulary.Tonable {
		tonable[glyph] = struct{}{}
		// Index by what stripping a tone actually produces: ApplyTone absorbs
		// a variation selector, so the stripped form of a toned emoji is not
		// the base. 🕵️‍♂️ is U+1F575 FE0F ZWJ ♂ FE0F, its toned form drops the
		// first FE0F, and stripping the tone therefore yields a sequence that
		// is in no table unless it is indexed like this.
		byStripped[StripTone(ApplyTone(glyph, skinTones[0]))] = glyph
	}
}

func isSkinTone(r rune) bool {
	for _, tone := range skinTones {
		if r == tone {
			return true
		}
	}
	return false
}

// ApplyTone returns the sequence for glyph wearing tone.
//
// The variation selector directly after the base is ABSORBED, not kept: ✌️ is
// U+270C FE0F but ✌🏽 is U+270C U+1F3FD. Appending instead would produce a
// string that renders wrong and, worse, differs from what every other client
// writes for the same reaction.
func ApplyTone(glyph string, tone rune) string {
	runes := []rune(glyph)
	if len(runes) == 0 {
		return glyph
	}

	rest := runes[1:]
	if len(rest) > 0 && rest[0] == 0xFE0F {
		rest = rest[1:]
	}

	out := make([]rune, 0, len(rest)+2)
	out = append(out, runes[0], tone)
	out = append(out, rest...)
	return string(out)
}

// StripTone removes every skin-tone modifier from glyph.
//
// Not an inverse of ApplyTone: the absorbed variation selector cannot be
// recovered. Use byStripped to get back to a base.
func StripTone(glyph string) string {
	var out strings.Builder
	for _, r := range glyph {
		if !isSkinTone(r) {
			out.WriteRune(r)
		}
	}
	return out.String()
}

// Normalize returns the canonical byte string for raw, and whether raw is an
// emoji this deployment stores at all.
//
// Mirrors core/lib/emoji/normalize.ts exactly; the shared fixture in
// core/lib/emoji/__fixtures__/normalize-cases.json is asserted from both sides
// so a change to one that is not made to the other fails a test.
func Normalize(raw string) (string, bool) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" || len([]rune(trimmed)) > maxLength {
		return "", false
	}

	// NFC settles the compositions it handles. It does NOT add or remove
	// U+FE0F, which is exactly why the tables below exist.
	composed := norm.NFC.String(trimmed)

	stripped := StripTone(composed)
	if stripped != composed {
		base, ok := byStripped[stripped]
		if !ok {
			return "", false
		}
		var tone rune
		for _, r := range composed {
			if isSkinTone(r) {
				tone = r
				break
			}
		}
		if tone == 0 {
			return "", false
		}
		return ApplyTone(base, tone), true
	}

	if mapped, ok := vocabulary.ByBare[composed]; ok {
		composed = mapped
	}
	if _, ok := canonical[composed]; !ok {
		return "", false
	}
	return composed, true
}

// IsCanonical reports whether raw is already exactly what would be stored.
// This is the check the write hook makes: the client is expected to have
// normalized, and a value that has not been is refused rather than repaired,
// so a buggy caller is loud instead of silently writing a second chip.
func IsCanonical(raw string) bool {
	normalized, ok := Normalize(raw)
	return ok && normalized == raw
}
