// Code generated by payloadgen (export-payload-types); DO NOT EDIT.
// Source of truth: the exported structs of Go package "sample".
// Regenerated by scripts/generate.ts on every install — never committed.

/** MultipartFieldJSON is the multipart form key carrying the JSON body. */
export const MultipartFieldJSON = 'json'

export const MaxAttachments = 20

/** Recipient is a single name/address pair. */
export interface Recipient {
    name: string
    email: string
}

/** SendRequest documents the full mapping surface. *\/ escape check. */
export interface SendRequest {
    /** To is the primary recipient list. */
    to: Recipient[]
    cc?: Recipient[]
    subject: string
    draft: boolean
    size: number
    ratio: number
    raw: string
    labels: Record<string, string>
    details: Details | null
    optional_details?: Details
    nested: number[][]
    ptr_list: (Details | null)[]
    'sent-at': string
}

/** Details is referenced before its declaration. */
export interface Details {
    ok: boolean
}
