import { spawnSync } from 'node:child_process'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { MIGRATIONS_DIR, memberDir, SERVER_DIR } from './paths'

// Regenerate core/types/pbSchema.ts + pbZodSchema.ts by invoking the
// standalone `export-types` Go binary against a fresh tmpdir pb_data
// with every on-disk app migration replayed. Replaces the practice of
// committing those files to git: the source of truth is now (manifests
// + migrations), and the schema files are regenerated by every
// `pnpm install` via the workspace-root postinstall → packages:generate
// chain.
//
// Standalone binary, not the full app: the export-types binary lives at
// core/server/cmd/export-types and imports only core/coreserver. Pure
// Go, no CGO, no feature-server dependency chain (mupdf, goheif, etc.).
// That keeps `pnpm install` lean — the only build prerequisite is `go`
// on PATH, no C libraries. The full `tinycld` binary exposes the same
// operation as a subcommand (`tinycld export-types`) for ad-hoc dev
// use, but the build pipeline uses the standalone binary to keep the
// Docker web-builder stage CGO-free.
//
// Run order matters: scripts/generate.ts MUST run first to refresh the
// pb_migrations/ symlinks from each installed package. Then this script
// can find them. packages:generate enforces the order via && chaining.
//
// Why a TS wrapper rather than inline shell in package.json: cross-
// platform. `mktemp -d` is unix-only, path joins differ on Windows, and
// a failure-to-cleanup leaves orphan tmpdirs in CI. Node handles all of
// that uniformly.
//
// Build vs run: in CI/dev we `go run` the binary on demand. In Docker
// the web-builder stage receives a pre-built binary via COPY --from=
// from a small pre-builder stage, and the TINYCLD_EXPORT_TYPES_BIN env
// var points at it so this script skips the `go run` step entirely.

// @tinycld/core lives nested inside the tinycld member (APP_DIR/core) in the
// merged layout. memberDir() resolves it the same way the generator does, so
// this can't drift if the member is renamed or core is relocated.
const CORE_DIR = memberDir('@tinycld/core')
const TYPES_DIR = path.resolve(CORE_DIR, 'types')
const CMD_DIR = path.resolve(CORE_DIR, 'server', 'cmd', 'export-types')

function run(cmd: string, args: string[], cwd: string): void {
    const result = spawnSync(cmd, args, { cwd, stdio: 'inherit' })
    if (result.status !== 0) {
        throw new Error(`${cmd} ${args.join(' ')} failed with status ${result.status ?? 'unknown'}`)
    }
}

function main(): void {
    if (!fs.existsSync(MIGRATIONS_DIR)) {
        // packages:generate creates this dir as part of its symlink dance; if
        // it's missing, the caller skipped that step. Bail with a clear error
        // instead of running export-types against a doc-less server.
        throw new Error(
            `pb_migrations not found at ${MIGRATIONS_DIR} — run 'pnpm run packages:generate' first (or rely on the && chain in package.json).`
        )
    }

    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tinycld-export-types-'))
    const pbData = path.join(tmp, 'pb_data')
    fs.mkdirSync(pbData, { recursive: true })

    const sharedArgs = ['--dir', pbData, '--migrationsDir', MIGRATIONS_DIR, '--typesDir', TYPES_DIR]

    try {
        const prebuilt = process.env.TINYCLD_EXPORT_TYPES_BIN
        if (prebuilt) {
            // Docker path: a pre-built binary was COPYed in. Invoke
            // directly, skipping the `go run` toolchain dependency.
            run(prebuilt, sharedArgs, SERVER_DIR)
        } else {
            // Local / CI path: invoke via `go run` from the cmd dir. The
            // Go toolchain must be on PATH. The standalone binary imports
            // only core/coreserver, so this build is CGO-free and fast.
            run('go', ['run', '.', ...sharedArgs], CMD_DIR)
        }
    } finally {
        fs.rmSync(tmp, { recursive: true, force: true })
    }
}

main()
