import * as fs from 'node:fs'
import { createRequire } from 'node:module'
import * as path from 'node:path'

// Source-of-truth directory for the lucide icon set. Each icon ships as
// `<kebab>.mjs` here with `sideEffects: false`. lucide-react-native's
// exports map deliberately hides everything other than `.` and `./icons`,
// so we can't resolve `lucide-react-native/package.json` or any `./dist/...`
// subpath. Resolve the root entry (which IS exported), then walk up to the
// package root and over into dist/esm/icons. Use createRequire because
// generate.ts runs as ESM under tsx.
const _require = createRequire(import.meta.url)
const LUCIDE_PKG_ROOT = (() => {
    const entry = _require.resolve('lucide-react-native') // .../dist/cjs/lucide-react-native.js
    return path.resolve(path.dirname(entry), '..', '..')
})()
const LUCIDE_ICONS_DIR = path.join(LUCIDE_PKG_ROOT, 'dist', 'esm', 'icons')

export interface IconFeatureInput {
    name: string // e.g. '@tinycld/mail' — used in error messages
    manifest: { nav?: { icon?: string } }
}

// 'hard-drive' → 'HardDrive'. Identifier-safe per lucide's own naming rules
// (icons never start with a digit, kebab segments are [a-z0-9]+).
export function kebabToPascal(name: string): string {
    return name
        .split('-')
        .filter(Boolean)
        .map(seg => seg[0].toUpperCase() + seg.slice(1))
        .join('')
}

function listLucideIconNames(): string[] {
    return fs
        .readdirSync(LUCIDE_ICONS_DIR)
        .filter(f => f.endsWith('.mjs') && !f.endsWith('.mjs.map'))
        .map(f => f.replace(/\.mjs$/, ''))
}

function levenshtein(a: string, b: string): number {
    if (a === b) return 0
    if (a.length === 0) return b.length
    if (b.length === 0) return a.length
    const dp = Array.from({ length: a.length + 1 }, () => new Array<number>(b.length + 1).fill(0))
    for (let i = 0; i <= a.length; i++) dp[i][0] = i
    for (let j = 0; j <= b.length; j++) dp[0][j] = j
    for (let i = 1; i <= a.length; i++) {
        for (let j = 1; j <= b.length; j++) {
            const cost = a[i - 1] === b[j - 1] ? 0 : 1
            dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + cost)
        }
    }
    return dp[a.length][b.length]
}

function closestMatch(name: string, candidates: string[]): string | null {
    let best: { name: string; distance: number } | null = null
    for (const c of candidates) {
        const d = levenshtein(name, c)
        if (best === null || d < best.distance) best = { name: c, distance: d }
    }
    if (best === null) return null
    if (best.distance > Math.ceil(name.length / 2)) return null
    return best.name
}

export function buildPackageIconsSource(features: IconFeatureInput[]): string {
    const valid = new Set(listLucideIconNames())

    const used: { kebab: string; sources: string[] }[] = []
    const seen = new Map<string, number>() // kebab → index in `used`

    for (const f of features) {
        const icon = f.manifest.nav?.icon
        if (!icon) continue
        const existing = seen.get(icon)
        if (existing !== undefined) {
            used[existing].sources.push(f.name)
            continue
        }
        if (!valid.has(icon)) {
            const suggestion = closestMatch(icon, [...valid])
            const hint = suggestion ? ` Did you mean '${suggestion}'?` : ''
            throw new Error(
                `[gen-icons] ${f.name}: nav.icon '${icon}' is not a known lucide icon.${hint} ` +
                    `See https://lucide.dev/icons/ for the full list (use the kebab-case URL slug).`
            )
        }
        seen.set(icon, used.length)
        used.push({ kebab: icon, sources: [f.name] })
    }

    used.sort((a, b) => a.kebab.localeCompare(b.kebab))

    const pascalNames = used.map(u => kebabToPascal(u.kebab))

    const lines: string[] = [
        '// Auto-generated by app/scripts/generate.ts — do not edit.',
        '// Source: nav.icon from every linked package manifest.',
        '// Only lucide icons are supported today; non-lucide assets are out of scope.',
    ]
    if (used.length === 0) {
        lines.push("import { type LucideIcon } from 'lucide-react-native'")
        lines.push('')
        lines.push('export const packageIcons: Record<string, LucideIcon> = {}')
        lines.push('')
        return lines.join('\n')
    }

    lines.push('import {')
    for (const p of pascalNames) lines.push(`    ${p},`)
    lines.push('    type LucideIcon,')
    lines.push("} from 'lucide-react-native'")
    lines.push('')
    lines.push('export const packageIcons: Record<string, LucideIcon> = {')
    for (let i = 0; i < used.length; i++) {
        const key = used[i].kebab
        const ident = pascalNames[i]
        const keyLiteral = /^[a-z][a-z0-9]*$/.test(key) ? key : `'${key}'`
        lines.push(`    ${keyLiteral}: ${ident},`)
    }
    lines.push('}')
    lines.push('')
    return lines.join('\n')
}
