import * as fs from 'node:fs'
import * as path from 'node:path'
import type { PackageManifest } from './load-manifest'

export interface ServerPkg {
    slug: string
    module: string
    serverRelPath: string // relative to SERVER_DIR
}

function slugToIdentifier(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

export function buildPackageExtensionsGo(pkgs: ServerPkg[]): string {
    if (pkgs.length === 0) {
        return [
            '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
            'package main',
            '',
            'import "github.com/pocketbase/pocketbase"',
            '',
            'func registerPackageExtensions(_ *pocketbase.PocketBase) {}',
            '',
        ].join('\n')
    }
    const imports = pkgs.map(p => `\t${slugToIdentifier(p.slug)} "${p.module}"`)
    const calls = pkgs.map(p => `\t${slugToIdentifier(p.slug)}.Register(app)`)
    return [
        '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
        'package main',
        '',
        'import (',
        '\t"github.com/pocketbase/pocketbase"',
        ...imports,
        ')',
        '',
        'func registerPackageExtensions(app *pocketbase.PocketBase) {',
        ...calls,
        '}',
        '',
    ].join('\n')
}

export function buildGoWork(coreRelPath: string, pkgs: ServerPkg[]): string {
    const uses = pkgs.map(p => `    ${p.serverRelPath}`)
    return ['go 1.25.0', '', 'use (', '    .', `    ${coreRelPath}`, ...uses, ')', ''].join('\n')
}

// A member server module (drive, calc, …) imports tinycld.org/core/* but pins
// it as require v0.0.0 — core is resolved only through a go.work, never
// downloaded. The app server gets one (buildGoWork); a member built on its own
// (e.g. `go build ./...` / `go test` from <member>/server) has nothing to
// resolve core, so the v0.0.0 require hits the proxy and fails with
// "unrecognized import path tinycld.org/core" / "missing go.sum entry".
//
// Emit a per-member go.work that replaces core with the local copy. The replace
// (not just a `use`) is required: Go resolves the v0.0.0 require during graph
// load before applying `use` substitution, so a bare `use` still triggers the
// proxy lookup. Living in go.work, the replace only affects the member's own
// standalone build — the assembled app build runs from app/server with its own
// go.work and is unaffected. It's gitignored in each member repo so it never
// ships into the assembled workspace.
export interface MemberGoReplace {
    module: string
    relPath: string
}

export function buildMemberGoWork(coreRelPath: string, extraReplaces: MemberGoReplace[] = []): string {
    const lines = ['go 1.25.0', '', 'use .', '', `replace tinycld.org/core => ${coreRelPath}`]
    for (const r of extraReplaces) {
        lines.push(`replace ${r.module} => ${r.relPath}`)
    }
    lines.push('')
    return lines.join('\n')
}

interface BundledPkgInput {
    manifest: PackageManifest
}

// Emit server/bundled-packages.json — consumed by core's Go
// coreserver.SyncBundledPackages at boot to seed the pkg_registry collection.
export function buildBundledPackages(features: BundledPkgInput[]): string {
    const rows = features.map(f => ({
        name: f.manifest.name,
        slug: f.manifest.slug,
        version: f.manifest.version,
        icon: f.manifest.nav?.icon ?? '',
        description: f.manifest.description ?? '',
        hasServer: !!f.manifest.server,
        navOrder: f.manifest.nav?.order ?? 0,
    }))
    return `${JSON.stringify(rows, null, 2)}\n`
}

// Replace (or create) a symlink at linkPath → target. Idempotent and safe
// under concurrent generator runs: if another process recreates the link
// between our unlink and create (EEXIST), we accept it when it already points
// at `target`, otherwise we retry the unlink+create once.
export function replaceSymlink(target: string, linkPath: string) {
    fs.mkdirSync(path.dirname(linkPath), { recursive: true })
    for (let attempt = 0; attempt < 2; attempt++) {
        try {
            // lstatSync (not existsSync) so a BROKEN existing symlink is still
            // detected and removed; it throws ENOENT only when nothing is there.
            fs.lstatSync(linkPath)
            fs.unlinkSync(linkPath)
        } catch {
            // nothing at linkPath — nothing to remove
        }
        try {
            fs.symlinkSync(target, linkPath)
            return
        } catch (err) {
            if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
                // A concurrent run recreated it. If it already points where we
                // want, we're done; otherwise loop to unlink + recreate.
                try {
                    if (fs.readlinkSync(linkPath) === target) return
                } catch {
                    // unreadable — fall through to retry
                }
                continue
            }
            throw err
        }
    }
}
