import { GO_VERSION } from './paths'
import { assertSafeImportField } from './validate-generated-field'

export interface CliPkg {
    slug: string
    module: string
    cliRelPath: string // relative to CLI_DIR
}

function slugToIdentifier(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

// cli/cli_extensions.go — mirrors buildPackageExtensionsGo for the CLI: each
// package's cli module contributes its Cobra commands via Register(root, c).
//
// Only slug and module are ever interpolated (validated below). A manifest's
// `cli.scopes` values contain ':', which SAFE_IMPORT_FIELD rightly rejects;
// they are consumed on the TS side and must never reach Go source.
export function buildCliExtensionsSource(pkgs: CliPkg[]): string {
    if (pkgs.length === 0) {
        return [
            '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
            'package main',
            '',
            'import (',
            '\t"github.com/spf13/cobra"',
            '',
            '\t"tinycld.org/cli/client"',
            ')',
            '',
            'func registerPackageCommands(_ *cobra.Command, _ *client.Client) {}',
            '',
        ].join('\n')
    }
    for (const p of pkgs) {
        assertSafeImportField('cli.slug', p.slug)
        assertSafeImportField('cli.module', p.module)
    }
    const imports = pkgs.map(p => `\t${slugToIdentifier(p.slug)} "${p.module}"`)
    const calls = pkgs.map(p => `\t${slugToIdentifier(p.slug)}.Register(root, c)`)
    return [
        '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
        'package main',
        '',
        'import (',
        '\t"github.com/spf13/cobra"',
        '',
        '\t"tinycld.org/cli/client"',
        ...imports,
        ')',
        '',
        'func registerPackageCommands(root *cobra.Command, c *client.Client) {',
        ...calls,
        '}',
        '',
    ].join('\n')
}

// cli/go.work — the assembled CLI build resolves each member's cli module
// through this. Unlike the server go.work there is no core line: the CLI is a
// pure HTTP client and (so far) imports nothing from tinycld.org/core. When a
// member cli first needs a core pure helper (fts.SanitizeQuery,
// quota.FormatBytes), add core/server here plus the fork replace — see
// buildGoWork/buildMemberGoWork in gen-server.ts for the mechanics.
//
// The replace mirrors the app server's `replace tinycld.org/core` (there it
// lives in the committed go.mod; the CLI's must ride in the generated go.work
// because the requiring go.mod files belong to member repos): members pin
// `require tinycld.org/cli v0.0.0`, and without the replace the module-graph
// load hits the proxy for that version before `use` substitution applies. It
// must be VERSIONED — an unversioned replace of a module that is itself a
// workspace `use` member is rejected by Go ("replaced at all versions").
export function buildCliGoWork(pkgs: CliPkg[]): string {
    const uses = pkgs.map(p => `    ${p.cliRelPath}`)
    const lines = [`go ${GO_VERSION}`, '', 'use (', '    .', ...uses, ')', '']
    if (pkgs.length > 0) {
        lines.push('replace tinycld.org/cli v0.0.0 => .', '')
    }
    return lines.join('\n')
}

// Per-member go.work so a member's cli module builds standalone (`go test`
// from <member>/cli). Members pin `require tinycld.org/cli v0.0.0`; the
// replace — not a bare `use` — is required for the same proxy-resolution
// reason documented on buildMemberGoWork.
export function buildMemberCliGoWork(cliRelPath: string): string {
    return [
        `go ${GO_VERSION}`,
        '',
        'use .',
        '',
        `replace tinycld.org/cli => ${cliRelPath}`,
        '',
    ].join('\n')
}
