export interface ConfigSettingsPanel {
    slug: string
    label: string
    component: string // subpath e.g. 'settings/provider'
}

export interface ConfigSystemSettingsPanel {
    slug: string
    label: string
    component: string // subpath e.g. 'system-settings/provider'
}

export interface ConfigSidebarContribution {
    target: string
    slot: string
    component: string // subpath e.g. 'sidebar-contributions/booking-pages'
    order: number
}

export interface ConfigSearch {
    adapter: string // package-exports subpath e.g. 'search-adapter'
    label?: string
}

export interface ConfigEventSource {
    target: string
    id: string
    label: string
    module: string // package-exports subpath e.g. 'calendar-source'
    color?: string
    order: number
}

export interface ConfigPkg {
    packageName: string
    slug: string
    schemaType: string // e.g. 'ContactsSchema'; '' for settings-only (must be non-empty when hasRegister is true)
    hasRegister: boolean
    hasSidebar: boolean
    hasProvider: boolean
    hasSeed: boolean
    settings: ConfigSettingsPanel[]
    systemSettings: ConfigSystemSettingsPanel[]
    slots: string[]
    sidebarContributions: ConfigSidebarContribution[]
    search?: ConfigSearch
    eventSources: ConfigEventSource[]
    eventSourceHost: boolean
    manifest: { name: string; slug: string; version: string; description: string } & Record<
        string,
        unknown
    >
}

import { assertSafeImportField } from './validate-generated-field'

function ident(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

function jsonLiteral(value: unknown): string {
    return JSON.stringify(value)
}

// Validate every manifest-derived string that gets interpolated UNESCAPED into
// the generated TS (import specifiers, identifiers, lazy import subpaths). The
// JSON-literal fields (manifest, slug/label in panels) are escaped by
// JSON.stringify and don't need this; these do.
function validateConfigPkg(p: ConfigPkg): void {
    assertSafeImportField('packageName', p.packageName)
    assertSafeImportField('slug', p.slug)
    if (p.schemaType) assertSafeImportField('schemaType', p.schemaType)
    for (const s of p.settings) assertSafeImportField('settings[].component', s.component)
    for (const s of p.systemSettings) {
        assertSafeImportField('systemSettings[].component', s.component)
    }
    for (const c of p.sidebarContributions) {
        assertSafeImportField('sidebarContributions[].component', c.component)
    }
    if (p.search) assertSafeImportField('search.adapter', p.search.adapter)
    for (const s of p.eventSources) assertSafeImportField('eventSources[].module', s.module)
}

function pushEventSourceLines(lines: string[], p: ConfigPkg): void {
    if (p.eventSources.length === 0) return
    lines.push('        eventSources: [')
    for (const s of p.eventSources) {
        // Same bare-thunk rationale as search: the module exports a hook.
        const color = s.color ? ` color: ${jsonLiteral(s.color)},` : ''
        lines.push(
            `            { target: ${jsonLiteral(s.target)}, id: ${jsonLiteral(s.id)}, label: ${jsonLiteral(s.label)},${color} order: ${s.order}, load: () => import('${p.packageName}/${s.module}') },`
        )
    }
    lines.push('        ],')
}

export function buildConfigSource(pkgs: ConfigPkg[]): string {
    for (const p of pkgs) {
        validateConfigPkg(p)
        if (p.hasRegister && !p.schemaType) {
            throw new Error(
                `ConfigPkg for '${p.packageName}': hasRegister is true but schemaType is empty`
            )
        }
    }
    const lines: string[] = ['// Auto-generated by app/scripts/generate.ts — do not edit']
    lines.push("import { definePackageEntry } from '@tinycld/core/lib/packages/config-types'")

    const needsLazy = pkgs.some(
        p =>
            p.hasSidebar ||
            p.hasProvider ||
            p.settings.length > 0 ||
            p.systemSettings.length > 0 ||
            p.sidebarContributions.length > 0
    )
    if (needsLazy) lines.push("import { lazy } from 'react'")

    for (const p of pkgs) {
        if (p.hasRegister) {
            lines.push(
                `import { registerCollections as ${ident(p.slug)}Register } from '${p.packageName}/collections'`
            )
            lines.push(`import type { ${p.schemaType} } from '${p.packageName}/types'`)
        }
    }

    lines.push('')
    lines.push('export const tinycldConfig = [')
    for (const p of pkgs) {
        const schemaParam = p.hasRegister ? p.schemaType : 'Record<string, never>'
        lines.push(`    definePackageEntry<${schemaParam}>()({`)
        lines.push(
            `        manifest: { ...(${jsonLiteral(p.manifest)} as const), packageName: ${jsonLiteral(p.packageName)} },`
        )
        if (p.hasRegister) lines.push(`        registerCollections: ${ident(p.slug)}Register,`)
        if (p.hasSidebar) {
            lines.push(`        sidebar: lazy(() => import('${p.packageName}/sidebar')),`)
        }
        if (p.hasProvider) {
            lines.push(`        provider: lazy(() => import('${p.packageName}/provider')),`)
        }
        if (p.settings.length > 0) {
            lines.push('        settings: [')
            for (const s of p.settings) {
                lines.push(
                    `            { slug: ${jsonLiteral(s.slug)}, label: ${jsonLiteral(s.label)}, Component: lazy(() => import('${p.packageName}/${s.component}')) },`
                )
            }
            lines.push('        ],')
        }
        if (p.systemSettings.length > 0) {
            lines.push('        systemSettings: [')
            for (const s of p.systemSettings) {
                lines.push(
                    `            { slug: ${jsonLiteral(s.slug)}, label: ${jsonLiteral(s.label)}, Component: lazy(() => import('${p.packageName}/${s.component}')) },`
                )
            }
            lines.push('        ],')
        }
        if (p.sidebarContributions.length > 0) {
            lines.push('        sidebarContributions: [')
            for (const c of p.sidebarContributions) {
                lines.push(
                    `            { target: ${jsonLiteral(c.target)}, slot: ${jsonLiteral(c.slot)}, order: ${c.order}, Component: lazy(() => import('${p.packageName}/${c.component}')) },`
                )
            }
            lines.push('        ],')
        }
        if (p.search) {
            lines.push('        search: {')
            if (p.search.label) lines.push(`            label: ${jsonLiteral(p.search.label)},`)
            // A bare thunk, NOT lazy(): the adapter exports a hook, not a
            // component, and React.lazy cannot wrap it.
            lines.push(`            load: () => import('${p.packageName}/${p.search.adapter}'),`)
            lines.push('        },')
        }
        pushEventSourceLines(lines, p)
        lines.push('    }),')
    }
    lines.push('] as const')
    lines.push('')

    const schemaTypes = pkgs.filter(p => p.hasRegister).map(p => p.schemaType)
    const merged = schemaTypes.length > 0 ? schemaTypes.join(' & ') : 'Record<string, never>'
    lines.push(`export type MergedPackageSchema = ${merged}`)
    lines.push('')
    return lines.join('\n')
}

export function buildSeedsSource(pkgs: ConfigPkg[]): string {
    const withSeeds = pkgs.filter(p => p.hasSeed)
    const lines: string[] = ['// Auto-generated by app/scripts/generate.ts — do not edit']
    for (const p of withSeeds) {
        assertSafeImportField('packageName', p.packageName)
        assertSafeImportField('slug', p.slug)
        lines.push(`import ${ident(p.slug)}Seed from '${p.packageName}/seed'`)
    }
    lines.push('')
    lines.push('export const tinycldSeeds = [')
    for (const p of withSeeds) {
        const deps = (p.manifest.dependencies as string[] | undefined) ?? []
        const depsLiteral = deps.length > 0 ? jsonLiteral(deps) : '[]'
        lines.push(
            `    { manifest: { slug: ${jsonLiteral(p.slug)}, dependencies: ${depsLiteral} }, seed: ${ident(p.slug)}Seed },`
        )
    }
    lines.push('] as const')
    lines.push('')
    return lines.join('\n')
}
