import * as fs from 'node:fs'
import * as path from 'node:path'
import type { PackageManifest } from './load-manifest'

export interface ServerPkg {
    slug: string
    module: string
    serverRelPath: string // relative to SERVER_DIR
}

function slugToIdentifier(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

export function buildPackageExtensionsGo(pkgs: ServerPkg[]): string {
    if (pkgs.length === 0) {
        return [
            '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
            'package main',
            '',
            'import "github.com/pocketbase/pocketbase"',
            '',
            'func registerPackageExtensions(_ *pocketbase.PocketBase) {}',
            '',
        ].join('\n')
    }
    const imports = pkgs.map(p => `\t${slugToIdentifier(p.slug)} "${p.module}"`)
    const calls = pkgs.map(p => `\t${slugToIdentifier(p.slug)}.Register(app)`)
    return [
        '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
        'package main',
        '',
        'import (',
        '\t"github.com/pocketbase/pocketbase"',
        ...imports,
        ')',
        '',
        'func registerPackageExtensions(app *pocketbase.PocketBase) {',
        ...calls,
        '}',
        '',
    ].join('\n')
}

export function buildGoWork(coreRelPath: string, pkgs: ServerPkg[]): string {
    const uses = pkgs.map(p => `    ${p.serverRelPath}`)
    return ['go 1.25.0', '', 'use (', '    .', `    ${coreRelPath}`, ...uses, ')', ''].join('\n')
}

interface BundledPkgInput {
    manifest: PackageManifest
}

// Emit server/bundled-packages.json — consumed by core's Go
// coreserver.SyncBundledPackages at boot to seed the pkg_registry collection.
export function buildBundledPackages(features: BundledPkgInput[]): string {
    const rows = features.map(f => ({
        name: f.manifest.name,
        slug: f.manifest.slug,
        version: f.manifest.version,
        icon: f.manifest.nav?.icon ?? '',
        description: f.manifest.description ?? '',
        hasServer: !!f.manifest.server,
        navOrder: f.manifest.nav?.order ?? 0,
    }))
    return `${JSON.stringify(rows, null, 2)}\n`
}

// Replace (or create) a symlink at linkPath → target. Idempotent and safe
// under concurrent generator runs: if another process recreates the link
// between our unlink and create (EEXIST), we accept it when it already points
// at `target`, otherwise we retry the unlink+create once.
export function replaceSymlink(target: string, linkPath: string) {
    fs.mkdirSync(path.dirname(linkPath), { recursive: true })
    for (let attempt = 0; attempt < 2; attempt++) {
        try {
            // lstatSync (not existsSync) so a BROKEN existing symlink is still
            // detected and removed; it throws ENOENT only when nothing is there.
            fs.lstatSync(linkPath)
            fs.unlinkSync(linkPath)
        } catch {
            // nothing at linkPath — nothing to remove
        }
        try {
            fs.symlinkSync(target, linkPath)
            return
        } catch (err) {
            if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
                // A concurrent run recreated it. If it already points where we
                // want, we're done; otherwise loop to unlink + recreate.
                try {
                    if (fs.readlinkSync(linkPath) === target) return
                } catch {
                    // unreadable — fall through to retry
                }
                continue
            }
            throw err
        }
    }
}
