#!/usr/bin/env node
import * as fs from 'node:fs'
import * as path from 'node:path'
import { pathToFileURL } from 'node:url'

// Single writer of every workspace-root coordination file. Two callers:
//   1. @tinycld/bootstrap, right after cloning, via bare `node <this file>`
//      (Node >=24 native type stripping) — so the FIRST `pnpm install`
//      resolves with correct version pins.
//   2. scripts/generate.ts (every install's postinstall) — so `git pull` +
//      `pnpm install` self-heals root files without re-running bootstrap.
//
// KEEP SELF-CONTAINED: caller 1 runs before any install, so this file may
// import only node:* builtins and must stay erasable TypeScript (no enums).
//
// Version pins come from core/package-versions.json (the SOURCE OF TRUTH,
// committed with core). Notable pin constraints preserved from the old
// bootstrap FRAMEWORK_OVERRIDES table:
//   - @tanstack/db / react-db / query-db-collection move in LOCKSTEP:
//     react-db and query-db-collection call internals of a specific db
//     version; letting one float produces a workspace that installs clean
//     and dies at import ("isCollection is not a function" /
//     "getLoadSubsetDemandKey").
//   - react-native-drax is a git FORK ref, not a semver: upstream lacks
//     fixes the kanban board drag depends on.
//
// TINYCLD_SERVER_REBUILD: the server (OTA) build pipeline sets this on its
// `pnpm install`. Builds must keep the pins the ACTIVE build shipped with
// (frozen at the embedded native binary's versions), and their
// pnpm-workspace.yaml is Go-written and carries a storeDir: this script must
// not touch either. Under the flag only the root biome.json is written.

const ALL_FEATURES = [
    'contacts',
    'mail',
    'calendar',
    'drive',
    'calc',
    'text',
    'google-takeout-import',
]
const ALL_MEMBERS = ['tinycld', 'tinycld/core', 'tinycld/package-scripts', ...ALL_FEATURES]
const NON_MEMBER_DIRS = ['bootstrap', 'utils', 'web']

// pnpm version pinned via package.json "packageManager" so corepack resolves
// the same pnpm everywhere (local, CI, EAS).
const PNPM_VERSION = '11.3.0'

const POSTINSTALL =
    'tsx scripts/link-members.ts && cd tinycld && pnpm run packages:generate && cd .. && tsx scripts/link-members.ts && cd tinycld && pnpm run assets:copy-pdfjs'

const DERIVED_DOC =
    'DERIVED FILE — do not edit. Generated by tinycld/scripts/write-workspace-root.ts from tinycld/core/package-versions.json (the source of truth). The Go OTA rebuild (core/server/pkgbuild) reads THIS copy to emit the pnpm overrides block on the server, where the root-writer must not re-derive it (see TINYCLD_SERVER_REBUILD).'

export function readCoreVersions(appDir: string): Record<string, string> {
    const file = path.join(appDir, 'core', 'package-versions.json')
    let raw: string
    try {
        raw = fs.readFileSync(file, 'utf8')
    } catch (err) {
        throw new Error(`[workspace-root] cannot read ${file}: ${(err as Error).message}`)
    }
    let parsed: Record<string, string>
    try {
        parsed = JSON.parse(raw)
    } catch (err) {
        throw new Error(`[workspace-root] malformed JSON in ${file}: ${(err as Error).message}`)
    }
    const { '//': _doc, ...pins } = parsed
    if (Object.keys(pins).length === 0) {
        throw new Error(`[workspace-root] ${file} has no version pins`)
    }
    for (const [key, value] of Object.entries(pins)) {
        if (typeof value !== 'string') {
            throw new Error(
                `[workspace-root] ${file}: pin "${key}" must be a string, got ${typeof value}`
            )
        }
    }
    return pins
}

// Mirrors the Go renderOverridesBlock (core/server/pkgbuild/assemble.go) so
// both generators emit byte-identical blocks: sorted for a stable diff,
// scoped names (leading @) single-quoted so YAML doesn't read them as
// anchors, plain names bare.
export function renderOverridesBlock(overrides: Record<string, string>): string {
    const lines = ['overrides:']
    for (const name of Object.keys(overrides).sort()) {
        const key = name.startsWith('@') ? `'${name}'` : name
        lines.push(`  ${key}: ${overrides[name]}`)
    }
    return lines.join('\n')
}

// Direct child dirs of wsRoot that look like a feature member already on
// disk (package.json + manifest.ts/js). Mirrors the generator's discovery so
// a CI-checked-out or custom member absent from ALL_MEMBERS still gets
// linked by pnpm.
function discoverPresentMembers(wsRoot: string): string[] {
    let entries: string[]
    try {
        entries = fs.readdirSync(wsRoot)
    } catch {
        return []
    }
    return entries.filter(name => {
        if (name === 'node_modules' || name.startsWith('.')) return false
        const dir = path.join(wsRoot, name)
        try {
            if (!fs.statSync(dir).isDirectory()) return false
        } catch {
            return false
        }
        const hasManifest =
            fs.existsSync(path.join(dir, 'manifest.ts')) ||
            fs.existsSync(path.join(dir, 'manifest.js'))
        return fs.existsSync(path.join(dir, 'package.json')) && hasManifest
    })
}

function memberUnion(wsRoot: string): string[] {
    return [...new Set([...ALL_MEMBERS, ...discoverPresentMembers(wsRoot)])]
}

function pnpmWorkspaceYaml(wsRoot: string, pins: Record<string, string>): string {
    const members = memberUnion(wsRoot)
        .map(m => `  - ${m}`)
        .join('\n')
    return [
        'nodeLinker: hoisted',
        'linkWorkspacePackages: true',
        'strictPeerDependencies: false',
        'enablePrePostScripts: true',
        '',
        '# pnpm 11 ships a default minimumReleaseAge supply-chain gate (~24h) that',
        '# rejects very freshly-published versions. The @tinycld/* libraries are',
        '# first-party and released in lockstep with these members, so a same-day',
        '# pbtsdb (or other @tinycld dep) bump must install immediately rather than',
        '# blocking install/CI for a day. Exclude them from the gate; third-party',
        '# packages still get the freshness window.',
        'minimumReleaseAgeExclude:',
        '  - pbtsdb',
        "  - '@tinycld/*'",
        '',
        'packages:',
        members,
        '',
        '# Build-script approvals (pnpm blocks dependency build scripts by default).',
        'allowBuilds:',
        '  esbuild: true',
        "  '@sentry/cli': true",
        '',
        '# Framework/native/styling version pins — derived from',
        '# tinycld/core/package-versions.json (the source of truth) by',
        "# tinycld/scripts/write-workspace-root.ts. These keep the OTA rebuild's",
        '# --no-frozen-lockfile install from drifting these deps off the embedded',
        '# native binary.',
        renderOverridesBlock(pins),
        '',
    ].join('\n')
}

// The directories watchman must NOT crawl. CRITICAL: the root node_modules is
// NOT ignored — under node-linker=hoisted it is the flat store Metro resolves
// EVERY dependency from; hiding it breaks module resolution. Only
// node_modules/.cache (Metro transform cache) is excluded. Member
// node_modules ARE ignored (near-empty under hoisting, pure crawl cost).
function watchmanConfig(wsRoot: string): string {
    const members = memberUnion(wsRoot)
    const memberDirs = members.flatMap(m => [`${m}/node_modules`, `${m}/.git`])
    const testResultDirs = members
        .filter(m => !m.startsWith('tinycld'))
        .map(m => `${m}/test-results`)
    const nonMemberDirs = NON_MEMBER_DIRS.flatMap(d => [
        `${d}/node_modules`,
        `${d}/.git`,
        `${d}/dist`,
    ])
    const ignoreDirs = [
        '.git',
        'node_modules/.cache',
        ...memberDirs,
        ...nonMemberDirs,
        'tinycld/ios',
        'tinycld/android',
        'tinycld/modules/app-updater/android/build',
        'tinycld/modules/app-updater/ios/build',
        'tinycld/.expo',
        'tinycld/dist',
        'tinycld/server/pb_data',
        'tinycld/server/pb_test_data',
        'tinycld/test-results',
        'tinycld/playwright-report',
        ...testResultDirs,
    ]
    const config = {
        enable_parallel_crawl: true,
        // fsevents_try_resync false (watchman's own default since 2021):
        // resync-from-journal usually fails on macOS and falls back to a full
        // recrawl — the 60s "syncToNow" stall on Metro start. Skip it.
        fsevents_try_resync: false,
        // 1.0s batches change notifications so an install/checkout burst
        // doesn't overflow the fsevents kernel queue on slow volumes; costs
        // ~1s of HMR detection lag. (default 0.01)
        fsevents_latency: 1.0,
        ignore_dirs: [...new Set(ignoreDirs)],
    }
    return `${JSON.stringify(config, null, 4)}\n`
}

function writeRootPackageJSON(wsRoot: string): void {
    const pkgPath = path.join(wsRoot, 'package.json')
    let existing: Record<string, unknown> = {}
    if (fs.existsSync(pkgPath)) {
        try {
            existing = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
        } catch {
            // Unparseable existing file — start from defaults
        }
    }
    const existingScripts =
        typeof existing.scripts === 'object' && existing.scripts !== null
            ? (existing.scripts as Record<string, string>)
            : {}
    const existingDevDeps =
        typeof existing.devDependencies === 'object' && existing.devDependencies !== null
            ? (existing.devDependencies as Record<string, string>)
            : {}
    const pkg = {
        name: '@tinycld/workspace',
        version: '0.0.0',
        private: true,
        type: 'module',
        ...existing,
        packageManager: `pnpm@${PNPM_VERSION}`,
        // Monorepo-detection hint for external tooling (EAS/expo archiver
        // keys off the npm `workspaces` field); pnpm reads members from
        // pnpm-workspace.yaml and ignores this.
        workspaces: memberUnion(wsRoot),
        scripts: {
            ...existingScripts,
            postinstall: POSTINSTALL,
        },
        devDependencies: {
            ...existingDevDeps,
            tsx: '^4.21.0',
        },
    }
    fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 4)}\n`)
}

// --- root biome.json (moved verbatim from scripts/generate.ts) ---
// Biome only searches UPWARD for config and the canonical biome.json lives at
// <ws-root>/tinycld/ — a sibling of the feature members. This root:true copy
// INLINES the canonical (a file-path `extends` silently drops `plugins`,
// biome #8488/#8524) with globs/plugin paths re-rooted one dir up. vcs.root
// stays 'tinycld' — only tinycld/.gitignore lists the generated artifacts.

function rerootGlob(glob: string, appDirName: string): string {
    const negated = glob.startsWith('!')
    const body = negated ? glob.slice(1) : glob
    if (body.startsWith('**') || body.startsWith('/')) return glob
    const rerooted = `${appDirName}/${body}`
    return negated ? `!${rerooted}` : rerooted
}

function rerootPluginPath(p: string, appDirName: string): string {
    if (path.isAbsolute(p)) return p
    return `./${appDirName}/${p.replace(/^\.\//, '')}`
}

type PluginEntry = string | { path: string; includes?: string[] }

function rerootPlugins(plugins: PluginEntry[], appDirName: string): PluginEntry[] {
    return plugins.map(entry =>
        typeof entry === 'string'
            ? rerootPluginPath(entry, appDirName)
            : { ...entry, path: rerootPluginPath(entry.path, appDirName) }
    )
}

function writeRootBiomeConfig(wsRoot: string, appDir: string): void {
    const appDirName = path.basename(appDir)
    const canonicalPath = path.join(appDir, 'biome.json')
    // A runtime rebuild's build tree may not carry the canonical config (it
    // never lints) — skip rather than abort the whole run.
    if (!fs.existsSync(canonicalPath)) {
        console.warn(
            `[workspace-root] ${canonicalPath} absent — skipping ws-root biome.json (lint-only)`
        )
        return
    }
    const canonical = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'))
    const config = {
        ...canonical,
        $schema: 'https://biomejs.dev/schemas/2.5.0/schema.json',
        root: true,
        vcs: { enabled: true, clientKind: 'git', useIgnoreFile: true, root: appDirName },
    }
    delete config.extends
    if (config.files?.includes) {
        config.files = {
            ...config.files,
            includes: config.files.includes.map((g: string) => rerootGlob(g, appDirName)),
        }
    }
    if (config.plugins) config.plugins = rerootPlugins(config.plugins, appDirName)
    fs.writeFileSync(path.join(wsRoot, 'biome.json'), `${JSON.stringify(config, null, 4)}\n`)
}

function warnIfPinsChanged(wsRoot: string, pins: Record<string, string>): void {
    const derivedPath = path.join(wsRoot, 'package-versions.json')
    if (!fs.existsSync(derivedPath)) return
    let previous: Record<string, string>
    try {
        previous = JSON.parse(fs.readFileSync(derivedPath, 'utf8'))
    } catch {
        return
    }
    const { '//': _doc, ...prevPins } = previous
    if (
        JSON.stringify(prevPins, Object.keys(prevPins).sort()) ===
        JSON.stringify(pins, Object.keys(pins).sort())
    )
        return
    console.warn(
        '[workspace-root] version pins changed — run pnpm install again to apply the new overrides to node_modules'
    )
}

export function writeWorkspaceRoot(
    wsRoot: string = path.resolve(import.meta.dirname, '..', '..'),
    appDir: string = path.resolve(import.meta.dirname, '..')
): void {
    writeRootBiomeConfig(wsRoot, appDir)
    if (process.env.TINYCLD_SERVER_REBUILD) {
        // Server (OTA) build: pins must stay frozen at the active build's
        // versions and the Go-written pnpm-workspace.yaml (with storeDir)
        // must not be clobbered. biome.json above is the only safe output.
        console.log(
            '[workspace-root] TINYCLD_SERVER_REBUILD set — leaving pin files and pnpm-workspace.yaml frozen'
        )
        return
    }
    const pins = readCoreVersions(appDir)
    warnIfPinsChanged(wsRoot, pins)
    writeRootPackageJSON(wsRoot)
    fs.writeFileSync(path.join(wsRoot, 'pnpm-workspace.yaml'), pnpmWorkspaceYaml(wsRoot, pins))
    fs.writeFileSync(
        path.join(wsRoot, 'package-versions.json'),
        `${JSON.stringify({ '//': DERIVED_DOC, ...pins }, null, 4)}\n`
    )
    fs.writeFileSync(path.join(wsRoot, '.watchmanconfig'), watchmanConfig(wsRoot))
    const npmrcPath = path.join(wsRoot, '.npmrc')
    if (!fs.existsSync(npmrcPath)) {
        fs.writeFileSync(
            npmrcPath,
            '# pnpm settings live in pnpm-workspace.yaml (pnpm 10+ reads them there).\n'
        )
    }
}

const invokedAsScript =
    process.argv[1] !== undefined &&
    import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (invokedAsScript) {
    writeWorkspaceRoot()
    console.log('[workspace-root] workspace root files written')
}
