// Package payloadgen emits TypeScript declarations from a feature package's
// Go "payload" package — the exported HTTP request/response structs a member
// declares via its manifest `payloads: { package }` block.
//
// The Go structs are the single source of truth for API payload shapes; the
// generated .ts lands in the app's lib/generated/ (@tinycld/app-generated) and
// is regenerated by scripts/generate.ts on every install, never committed.
//
// Unlike coreserver's collection-driven schema generator, this one parses Go
// source with go/ast — it never imports the feature package, so the standalone
// binary stays CGO-free and free of feature-server dependencies (the same
// constraint documented in cmd/export-types). That only works because payload
// packages are required to be self-contained: any import beyond the small
// whitelist, or any type this generator cannot faithfully map, is a hard
// error — a payload contract must never be emitted best-effort.
package payloadgen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// importWhitelist is the set of imports a payload package may use. Anything
// else would either require cross-package type resolution (which go/ast cannot
// do without loading the full dependency graph) or drag feature-server deps
// into the payload surface.
var importWhitelist = map[string]bool{
	"time": true,
}

var identRe = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

// Generate parses the single Go package at srcDir and returns the TypeScript
// source for its exported struct types and exported basic-literal consts.
func Generate(srcDir string) (string, error) {
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return "", fmt.Errorf("read payload dir: %w", err)
	}
	var fileNames []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		fileNames = append(fileNames, name)
	}
	if len(fileNames) == 0 {
		return "", fmt.Errorf("payload dir %s contains no Go files", srcDir)
	}
	sort.Strings(fileNames)

	fset := token.NewFileSet()
	files := make(map[string]*ast.File, len(fileNames))
	pkgName := ""
	for _, fileName := range fileNames {
		file, err := parser.ParseFile(fset, filepath.Join(srcDir, fileName), nil, parser.ParseComments)
		if err != nil {
			return "", fmt.Errorf("parse %s: %w", fileName, err)
		}
		if pkgName == "" {
			pkgName = file.Name.Name
		} else if file.Name.Name != pkgName {
			return "", fmt.Errorf("payload dir %s must contain exactly one package, found %q and %q", srcDir, pkgName, file.Name.Name)
		}
		files[fileName] = file
	}

	g := &generator{types: map[string]*ast.TypeSpec{}}

	// Pass 1: validate imports, index every type declaration, and collect
	// declarations in a deterministic order (file name, then source order).
	for _, fileName := range fileNames {
		file := files[fileName]
		for _, imp := range file.Imports {
			pathValue, _ := strconv.Unquote(imp.Path.Value)
			if !importWhitelist[pathValue] {
				return "", fmt.Errorf("%s imports %q — payload packages must be self-contained (allowed: time)", fileName, pathValue)
			}
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch gen.Tok {
			case token.TYPE:
				for _, spec := range gen.Specs {
					ts := spec.(*ast.TypeSpec)
					g.types[ts.Name.Name] = ts
					if ts.Name.IsExported() {
						doc := ts.Doc
						if doc == nil && len(gen.Specs) == 1 {
							doc = gen.Doc
						}
						g.order = append(g.order, typeDecl{spec: ts, doc: doc})
					}
				}
			case token.CONST:
				for _, spec := range gen.Specs {
					vs := spec.(*ast.ValueSpec)
					for i, name := range vs.Names {
						if !name.IsExported() {
							continue
						}
						if i >= len(vs.Values) {
							return "", fmt.Errorf("const %s has no literal value — payload consts must be explicit basic literals", name.Name)
						}
						lit, ok := vs.Values[i].(*ast.BasicLit)
						if !ok {
							return "", fmt.Errorf("const %s is not a basic literal — payload consts must be explicit basic literals", name.Name)
						}
						tsValue, err := tsLiteral(lit)
						if err != nil {
							return "", fmt.Errorf("const %s: %w", name.Name, err)
						}
						doc := vs.Doc
						if doc == nil && len(gen.Specs) == 1 {
							doc = gen.Doc
						}
						g.consts = append(g.consts, constDecl{name: name.Name, value: tsValue, doc: doc})
					}
				}
			}
		}
	}

	// Pass 2: emit.
	var b strings.Builder
	b.WriteString("// Code generated by payloadgen (export-payload-types); DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source of truth: the exported structs of Go package %q.\n", pkgName)
	b.WriteString("// Regenerated by scripts/generate.ts on every install — never committed.\n")

	for _, c := range g.consts {
		b.WriteString("\n")
		writeJSDoc(&b, c.doc, "")
		fmt.Fprintf(&b, "export const %s = %s\n", c.name, c.value)
	}

	for _, td := range g.order {
		src, err := g.emitInterface(td)
		if err != nil {
			return "", err
		}
		b.WriteString("\n")
		b.WriteString(src)
	}

	return b.String(), nil
}

type typeDecl struct {
	spec *ast.TypeSpec
	doc  *ast.CommentGroup
}

type constDecl struct {
	name  string
	value string
	doc   *ast.CommentGroup
}

type generator struct {
	types  map[string]*ast.TypeSpec
	order  []typeDecl
	consts []constDecl
}

func (g *generator) emitInterface(td typeDecl) (string, error) {
	name := td.spec.Name.Name
	st, ok := td.spec.Type.(*ast.StructType)
	if !ok {
		return "", fmt.Errorf("type %s is not a struct — payload packages may only export structs and basic-literal consts", name)
	}

	var b strings.Builder
	writeJSDoc(&b, td.doc, "")
	fmt.Fprintf(&b, "export interface %s {\n", name)
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			return "", fmt.Errorf("%s embeds %s — embedded fields are not supported in payload structs", name, exprString(field.Type))
		}
		for _, fieldName := range field.Names {
			// encoding/json skips unexported fields; mirror that.
			if !fieldName.IsExported() {
				continue
			}
			prop, err := g.emitField(name, fieldName.Name, field)
			if err != nil {
				return "", err
			}
			if prop == "" {
				continue // json:"-"
			}
			writeJSDoc(&b, field.Doc, "    ")
			b.WriteString(prop)
		}
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func (g *generator) emitField(structName, fieldName string, field *ast.Field) (string, error) {
	if field.Tag == nil {
		return "", fmt.Errorf("%s.%s has no json tag — every payload field must name its wire key explicitly", structName, fieldName)
	}
	tag := reflect.StructTag(strings.Trim(field.Tag.Value, "`"))
	jsonTag, ok := tag.Lookup("json")
	if !ok {
		return "", fmt.Errorf("%s.%s has no json tag — every payload field must name its wire key explicitly", structName, fieldName)
	}
	wireName, opts, hasOpts := strings.Cut(jsonTag, ",")
	if wireName == "-" && !hasOpts {
		return "", nil // `json:"-,"` would mean a literal "-" key; bare "-" skips
	}
	if wireName == "" {
		return "", fmt.Errorf("%s.%s json tag does not name its wire key — implicit Go-name keys are not allowed", structName, fieldName)
	}
	omitempty := false
	for opt := range strings.SplitSeq(opts, ",") {
		if opt == "omitempty" {
			omitempty = true
		}
	}

	var tsType string
	optional := omitempty
	if star, isPtr := field.Type.(*ast.StarExpr); isPtr {
		inner, err := g.tsType(star.X)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", structName, fieldName, err)
		}
		if omitempty {
			// An omitted-when-nil pointer never marshals null on the wire.
			tsType = inner
		} else {
			tsType = inner + " | null"
		}
	} else {
		var err error
		tsType, err = g.tsType(field.Type)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", structName, fieldName, err)
		}
	}

	prop := wireName
	if !identRe.MatchString(prop) {
		prop = "'" + prop + "'"
	}
	q := ""
	if optional {
		q = "?"
	}
	return fmt.Sprintf("    %s%s: %s\n", prop, q, tsType), nil
}

func (g *generator) tsType(expr ast.Expr) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "byte", "rune":
			return "number", nil
		case "any":
			return "", fmt.Errorf("`any` defeats the typed contract — declare a struct for the shape")
		}
		decl, exists := g.types[t.Name]
		if !exists {
			return "", fmt.Errorf("type %s is not declared in the payload package", t.Name)
		}
		if !decl.Name.IsExported() {
			return "", fmt.Errorf("type %s is unexported — every type reachable from a payload must be exported", t.Name)
		}
		return t.Name, nil
	case *ast.ArrayType:
		if ident, isIdent := t.Elt.(*ast.Ident); isIdent && ident.Name == "byte" {
			return "string", nil // encoding/json marshals []byte as base64
		}
		inner, err := g.tsType(t.Elt)
		if err != nil {
			return "", err
		}
		if strings.ContainsAny(inner, " |") {
			return "(" + inner + ")[]", nil
		}
		return inner + "[]", nil
	case *ast.MapType:
		key, isIdent := t.Key.(*ast.Ident)
		if !isIdent || key.Name != "string" {
			return "", fmt.Errorf("map key %s is not string — JSON object keys are strings", exprString(t.Key))
		}
		value, err := g.tsType(t.Value)
		if err != nil {
			return "", err
		}
		return "Record<string, " + value + ">", nil
	case *ast.StarExpr:
		inner, err := g.tsType(t.X)
		if err != nil {
			return "", err
		}
		return inner + " | null", nil
	case *ast.SelectorExpr:
		if pkg, isIdent := t.X.(*ast.Ident); isIdent && pkg.Name == "time" && t.Sel.Name == "Time" {
			return "string", nil // RFC 3339 on the wire
		}
		return "", fmt.Errorf("cross-package type %s — payload packages must be self-contained", exprString(t))
	case *ast.InterfaceType:
		return "", fmt.Errorf("`interface{}` defeats the typed contract — declare a struct for the shape")
	default:
		return "", fmt.Errorf("unsupported type %s", exprString(expr))
	}
}

// tsLiteral converts a Go basic literal to TypeScript source.
func tsLiteral(lit *ast.BasicLit) (string, error) {
	switch lit.Kind {
	case token.STRING:
		unquoted, err := strconv.Unquote(lit.Value)
		if err != nil {
			return "", fmt.Errorf("unreadable string literal %s", lit.Value)
		}
		escaped := strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`).Replace(unquoted)
		return "'" + escaped + "'", nil
	case token.INT, token.FLOAT:
		return lit.Value, nil
	default:
		return "", fmt.Errorf("unsupported literal kind %s", lit.Kind)
	}
}

// writeJSDoc renders a Go doc comment as a JSDoc block at the given indent.
func writeJSDoc(b *strings.Builder, doc *ast.CommentGroup, indent string) {
	if doc == nil {
		return
	}
	text := strings.TrimSpace(doc.Text())
	if text == "" {
		return
	}
	// A literal */ inside the comment would terminate the JSDoc block early —
	// this is the one place Go source text flows into TS source verbatim.
	text = strings.ReplaceAll(text, "*/", "*\\/")
	lines := strings.Split(text, "\n")
	if len(lines) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, line := range lines {
		fmt.Fprintf(b, "%s * %s\n", indent, strings.TrimRight(line, " "))
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

func exprString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	default:
		return fmt.Sprintf("%T", expr)
	}
}
