/**
 * Regenerates every emoji artifact from one upstream source, so they cannot
 * drift from each other:
 *
 *   lib/emoji/canonical-forms.ts            the storable vocabulary (base bundle)
 *   lib/emoji/__fixtures__/upstream-tones.json  tone-derivation test fixture
 *   ui/emoji-picker/emoji-data.ts           the picker table (lazy chunk)
 *
 * Source: emoji-picker-react's prepared data, itself built from emojibase.
 * Clone it next to this workspace and point EMOJI_SOURCE at it:
 *
 *   git clone https://github.com/ealush/emoji-picker-react ~/code/vendor/emoji-picker-react
 *   cd tinycld/core && pnpm exec tsx scripts/build-emoji-data.ts
 *
 * Deterministic: every collection is sorted before it is written, so a re-run
 * with an unchanged source produces a byte-identical file and an upstream
 * refresh produces a reviewable diff.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const CORE = join(HERE, '..')

const EMOJI_SOURCE =
    process.env.EMOJI_SOURCE ??
    join(homedir(), 'code/vendor/emoji-picker-react/src/data/emojis.json')

/** Skin tone modifiers, in the order lib/emoji/tones.ts lists them. */
const TONES = ['1f3fb', '1f3fc', '1f3fd', '1f3fe', '1f3ff'] as const

/** Search terms kept per emoji. Upstream ships ~6.3; the table halves at 3. */
const KEYWORDS_KEPT = 3

/**
 * Subdivision flags we keep. They share the 1f3f4-e0067 tag-sequence prefix
 * with nothing else we ship, so without this list the country-flag filter
 * would take them too.
 */
const KEPT_SUBDIVISIONS = new Set([
    '1f3f4-e0067-e0062-e0065-e006e-e0067-e007f', // England
    '1f3f4-e0067-e0062-e0073-e0063-e0074-e007f', // Scotland
    '1f3f4-e0067-e0062-e0077-e006c-e0073-e007f', // Wales
])

interface UpstreamEmoji {
    n: string[]
    u: string
    v?: string[]
    a?: string
}

interface Upstream {
    emojis: Record<string, UpstreamEmoji[]>
}

const toGlyph = (unified: string) =>
    unified
        .split('-')
        .map(hex => String.fromCodePoint(Number.parseInt(hex, 16)))
        .join('')

/**
 * Country flags are dropped: 259 regional-indicator pairs plus the
 * subdivision tag sequences we do not keep. They are ~14% of the set, are
 * rarely used as reactions, and carry a political surface we would rather the
 * picker not present.
 */
const isCountryFlag = (unified: string) =>
    /^1f1[e-f][0-9a-f]-1f1[e-f][0-9a-f]$/.test(unified) ||
    (unified.startsWith('1f3f4-e0067') && !KEPT_SUBDIVISIONS.has(unified))

/**
 * Two-person sequences (couples, wrestling, holding hands) take one tone PER
 * PERSON — 25 variants each — and the toned form is a structurally different
 * sequence, not the base plus a modifier. They are offered toneless only.
 */
const isMultiTone = (emoji: UpstreamEmoji) =>
    !!emoji.v?.length &&
    Math.max(...emoji.v.map(v => v.split('-').filter(p => TONES.includes(p as never)).length)) > 1

function main() {
    const upstream = JSON.parse(readFileSync(EMOJI_SOURCE, 'utf8')) as Upstream

    const categories = Object.entries(upstream.emojis).filter(([name]) => name !== 'custom')
    const kept = categories.flatMap(([category, list]) =>
        list.filter(e => !isCountryFlag(e.u)).map(e => ({ ...e, category }))
    )

    const tonable = kept.filter(e => e.v?.length && !isMultiTone(e))
    const multiTone = kept.filter(isMultiTone)

    // --- canonical-forms.ts : the storable vocabulary -----------------------
    // Base sequences only. Toned forms are validated by reconstruction, not
    // storage — listing the 1550 derived variants would triple a file that
    // has to stay in the base bundle (reaction chips normalize synchronously).
    const bases = [...new Set(kept.map(e => toGlyph(e.u)))].sort()
    const tonableGlyphs = [...new Set(tonable.map(e => toGlyph(e.u)))].sort()
    const byBare: Record<string, string> = {}
    for (const emoji of kept) {
        if (!emoji.u.includes('fe0f')) continue
        const bare = toGlyph(emoji.u.replaceAll('-fe0f', ''))
        if (!bases.includes(bare)) byBare[bare] = toGlyph(emoji.u)
    }
    const bareSorted = Object.fromEntries(
        Object.entries(byBare).sort(([a], [b]) => a.localeCompare(b))
    )

    writeFileSync(
        join(CORE, 'lib/emoji/canonical-forms.ts'),
        `// GENERATED by core/scripts/build-emoji-data.ts — do not hand-edit.
//
// The vocabulary the reactions column accepts. Three tables:
//
//  CANONICAL_EMOJI  — every base sequence (${bases.length}). Toned forms are NOT
//                     listed: normalize() strips the tone and checks the base,
//                     because applyTone/stripTone are proven exact against the
//                     full upstream variation set (see tones.test.ts). Listing
//                     the ${tonableGlyphs.length * TONES.length} derived forms would triple this file for nothing.
//  TONABLE_EMOJI    — bases that legitimately take a skin tone (${tonableGlyphs.length}), so a
//                     tone on anything else is rejected rather than stored.
//  CANONICAL_BY_BARE— bare forms that gain a variation selector (${Object.keys(bareSorted).length}).
//
// Why a table and not a regex: Unicode's Emoji property is true for bare
// digits ("5") and the obvious sequence regex REJECTS the 15 keycap emoji, so
// a property-based test both over- and under-matches. See normalize.ts.

export const CANONICAL_EMOJI: ReadonlySet<string> = new Set(${JSON.stringify(bases)})

export const TONABLE_EMOJI: ReadonlySet<string> = new Set(${JSON.stringify(tonableGlyphs)})

export const CANONICAL_BY_BARE: Readonly<Record<string, string>> = ${JSON.stringify(bareSorted)}
`
    )

    // --- upstream-tones.json : the derivation fixture -----------------------
    const fixture: Record<string, (string | null)[]> = {}
    for (const emoji of tonable) {
        fixture[emoji.u] = TONES.map(t => emoji.v?.find(v => v.includes(t)) ?? null)
    }
    writeFileSync(
        join(CORE, 'lib/emoji/__fixtures__/upstream-tones.json'),
        JSON.stringify({
            '//':
                'GENERATED by core/scripts/build-emoji-data.ts from emoji-picker-react. ' +
                'Each key is a toneless unified sequence; the value is its five toned forms in ' +
                'SKIN_TONES order. multiTone lists the two-person sequences deliberately excluded.',
            tonable: fixture,
            multiTone: multiTone.map(e => e.u).sort(),
        })
    )

    // --- emoji-data.ts : the picker table (lazy chunk) ----------------------
    // Upstream sorts names shortest-first, so the TAIL is the most descriptive
    // ('face','grin','grinning face'). Keep the last few, not the first.
    // Grouped by category rather than a field per record: the category key
    // repeated 1647 times costs ~21KB, and the picker renders by section
    // anyway, so the grouping is the shape it actually wants.
    const grouped = categories.map(([category, list]) => ({
        c: category,
        e: list
            .filter(e => !isCountryFlag(e.u))
            .map(emoji => {
                const record: { u: string; n: string[]; t?: 1 } = {
                    u: emoji.u,
                    n: emoji.n.slice(-KEYWORDS_KEPT),
                }
                if (emoji.v?.length && !isMultiTone(emoji)) record.t = 1
                return record
            }),
    }))
    const records = grouped.flatMap(g => g.e)

    writeFileSync(
        join(CORE, 'ui/emoji-picker/emoji-data.ts'),
        `// GENERATED by core/scripts/build-emoji-data.ts — do not hand-edit.
//
// ${records.length} emoji: the full upstream set minus the 259 country flags.
// ${KEYWORDS_KEPT} search terms each (upstream ships ~6.3), which is most of why this
// file is ~${Math.round(JSON.stringify(records).length / 1024)}KB rather than ~160KB.
//
// REACHED ONLY THROUGH import() — see ui/emoji-picker/use-emoji-data.ts.
// Metro does not tree-shake, so a static import would put this in the base
// bundle for every user on every platform, including deployments with no
// package that uses a picker. bundle-sentinel.test.tsx guards that.
//
// \`t: 1\` marks an emoji that takes a skin tone; the toned sequences are
// computed by lib/emoji/tones.ts rather than stored.

export interface EmojiRecord {
    /** Hyphenated unified codepoints, e.g. "1f44d" or "1f9d1-200d-1f680". */
    u: string
    /** Search terms, most descriptive last. */
    n: string[]
    /** Present when the emoji takes a skin tone. */
    t?: 1
}

export interface EmojiCategory {
    /** Category key, e.g. "smileys_people". */
    c: string
    e: readonly EmojiRecord[]
}

export const EMOJI_DATA: readonly EmojiCategory[] = ${JSON.stringify(grouped)}
`
    )

    const size = (p: string) => `${(readFileSync(p).length / 1024).toFixed(1)}KB`
    console.log(`emoji           ${records.length}`)
    console.log(`  tonable       ${tonableGlyphs.length}`)
    console.log(`  multi-tone    ${multiTone.length} (offered toneless)`)
    console.log(
        `canonical-forms ${size(join(CORE, 'lib/emoji/canonical-forms.ts'))}  (base bundle)`
    )
    console.log(
        `emoji-data      ${size(join(CORE, 'ui/emoji-picker/emoji-data.ts'))}  (lazy chunk)`
    )
}

main()
