import { existsSync } from 'node:fs'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterAll, describe, expect, it } from 'vitest'
import { bundleWebViewEditor } from '../../webview-bundler/build'

/**
 * Bundles the real WebView editor source.
 *
 * The native markdown path has no mechanical coverage below this line — an
 * unresolvable import or a broken entry surfaces only as a blank WebView on a
 * device. This catches that in CI without one.
 */
const SOURCE_DIR = resolve(__dirname, '../webview/source')
const CORE_ROOT = resolve(__dirname, '../../../..')
const APP_ROOT = resolve(CORE_ROOT, '..')
const WS_ROOT = resolve(APP_ROOT, '..')

let tempDir: string | null = null

afterAll(async () => {
    if (tempDir) await rm(tempDir, { recursive: true, force: true })
})

describe('rich editor WebView bundle', () => {
    it('bundles to a self-contained page', async () => {
        tempDir = await mkdtemp(join(tmpdir(), 'rich-editor-bundle-'))
        const outFile = join(tempDir, 'editorHtml.ts')

        const result = await bundleWebViewEditor({
            entryHtml: join(SOURCE_DIR, 'index.html'),
            entryScript: join(SOURCE_DIR, 'entry.tsx'),
            outFile,
            nodePaths: [join(APP_ROOT, 'node_modules'), join(WS_ROOT, 'node_modules')],
        })

        expect(existsSync(outFile)).toBe(true)
        const emitted = await readFile(outFile, 'utf-8')
        expect(emitted).toContain('export const editorHtml')

        // Assert against the HTML the WebView actually receives, not the
        // module source — the emitted file escapes it into a JS string
        // literal, so this also proves the escaping survives a round-trip.
        const html = JSON.parse(
            emitted.slice(emitted.indexOf('"'), emitted.lastIndexOf('"') + 1)
        ) as string

        expect(html).toContain('<div id="root">')
        // The page must carry its own script inline — a leftover <script src>
        // would load nothing inside a WebView with no origin to resolve it.
        expect(html).not.toMatch(/<script\s+src=/)

        // Guards against a bundle that "succeeds" while tree-shaking the
        // editor away: markdown being native to this page is the whole point.
        expect(result.htmlSize).toBeGreaterThan(100_000)
        expect(html).toContain('ProseMirror')

        // The collaboration stack has to be in the page, not just imported by
        // it. If Collaboration were tree-shaken away the editor would still
        // mount, still accept typing, and silently sync with nobody — a
        // failure invisible to every other test here, and on a device
        // indistinguishable from a network problem.
        //
        // `y-sync` is y-prosemirror's plugin key and `beforeAllTransactions` a
        // yjs internal: both survive minification because they are string
        // literals / exported names, whereas the extension's own identifiers
        // do not.
        expect(html).toContain('y-sync')
        expect(html).toContain('beforeAllTransactions')

        // Carets need CSS to be visible at all — the extension only sets a
        // border COLOR inline, so an unstyled caret is a zero-width nothing.
        // The rules once carried tiptap v2's singular class name and silently
        // matched nothing on every platform.
        expect(html).toContain('collaboration-carets__caret')
    }, 120_000)

    it('has an on-disk bundle built from the current source', async () => {
        // The artifact the native hook imports is gitignored and regenerated by
        // the build, so editing anything under webview/source/ without
        // rebuilding leaves every test above green while a device runs the OLD
        // page — the awareness relay simply absent, with no error to see.
        //
        // Skipped rather than failed when it is missing: a fresh clone has not
        // run the generator yet, and that is not a stale bundle.
        const artifact = join(SOURCE_DIR, '../build/editorHtml.ts')
        if (!existsSync(artifact)) return

        const module = await readFile(artifact, 'utf-8')
        // The artifact holds the page as an escaped JS string literal, so read
        // it the way the bundle test above does rather than grepping the module.
        const built = JSON.parse(
            module.slice(module.indexOf('"'), module.lastIndexOf('"') + 1)
        ) as string

        expect(built).toContain('collaboration-carets__caret')
        // The relay's namespace literal, which minification preserves. Absent
        // from a bundle built before the awareness relay landed — checked
        // against the previous artifact rather than assumed.
        expect(built).toContain('"awareness"')
    })
})
